name: Deploy

on:
  push:
    branches: [main]
    
jobs:
  deploy-to-staging:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.IMAGE_PUSH_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.IMAGE_PUSH_AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build the Docker image
        run: |
          TAG=$(git rev-parse --short HEAD)
          docker build -f Dockerfile -t ec2-web .
          docker tag ec2-web 851725348382.dkr.ecr.sa-east-1.amazonaws.com/ec2-aws:$(echo $TAG)
          docker push 851725348382.dkr.ecr.sa-east-1.amazonaws.com/ec2-aws:$(echo $TAG)
          docker tag ec2-web 851725348382.dkr.ecr.sa-east-1.amazonaws.com/ec2-aws:latest
          docker push 851725348382.dkr.ecr.sa-east-1.amazonaws.com/ec2-aws:latest

      - name: Update staging server
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} > ~/.ssh/known_hosts
          ssh ec2-user@${{ secrets.DEPLOY_HOST }} "./update_server.sh"
